---
- name: Define large deployment node readiness targets
  ansible.builtin.set_fact:
    personas_deployment_primary_node:
      ip: "{{ personas_deployment_pan1_ip }}"
      hostname: "{{ personas_deployment_pan1_hostname | default(personas_deployment_ise_base_hostname | lower ~ '-pan-server-1', true) }}"
    personas_deployment_secondary_nodes:
      - ip: "{{ personas_deployment_pan2_ip }}"
        hostname: "{{ personas_deployment_pan2_hostname | default(personas_deployment_ise_base_hostname | lower ~ '-pan-server-2', true) }}"
      - ip: "{{ personas_deployment_mnt1_ip }}"
        hostname: "{{ personas_deployment_mnt1_hostname | default(personas_deployment_ise_base_hostname | lower ~ '-mnt-server-1', true) }}"
      - ip: "{{ personas_deployment_mnt2_ip }}"
        hostname: "{{ personas_deployment_mnt2_hostname | default(personas_deployment_ise_base_hostname | lower ~ '-mnt-server-2', true) }}"
      - ip: "{{ personas_deployment_psn1_ip }}"
        hostname: "{{ personas_deployment_psn1_hostname | default(personas_deployment_ise_base_hostname | lower ~ '-psn-server-1', true) }}"
      - ip: "{{ personas_deployment_psn2_ip }}"
        hostname: "{{ personas_deployment_psn2_hostname | default(personas_deployment_ise_base_hostname | lower ~ '-psn-server-2', true) }}"

- name: Build large deployment cluster node list
  ansible.builtin.set_fact:
    personas_deployment_cluster_nodes: "{{ [personas_deployment_primary_node] + personas_deployment_secondary_nodes }}"

- name: Wait for large deployment node readiness
  ansible.builtin.include_tasks: wait_for_node_readiness.yml

- name: Register the nodes to the cluster except the standby MNT
  cisco.ise.node_deployment:
    ise_hostname: "{{ personas_deployment_pan1_ip }}"
    ise_username: "{{ personas_deployment_ise_username }}"
    ise_password: "{{ personas_deployment_ise_password }}"
    ise_verify: "{{ personas_deployment_ise_verify }}"
    ise_single_request_timeout: "{{ personas_deployment_ise_single_request_timeout }}"
    ise_version: "{{ personas_deployment_ise_version }}"
    state: present
    allowCertImport: true
    fqdn: "{{ item.fqdn }}"
    hostname: "{{ item.hostname }}"
    userName: "{{ personas_deployment_ise_username }}"
    password: "{{ personas_deployment_ise_password }}"
    roles: "{{ item.roles }}"
    services: "{{ item.services }}"
  loop:
    - fqdn: "{{ personas_deployment_pan2_hostname | default(personas_deployment_ise_base_hostname | lower ~ '-pan-server-2', true) }}.{{ personas_deployment_ise_domain }}"
      hostname: "{{ personas_deployment_pan2_hostname | default(personas_deployment_ise_base_hostname | lower ~ '-pan-server-2', true) }}"
      roles:
        - SecondaryAdmin
      services: []
    - fqdn: "{{ personas_deployment_mnt1_hostname | default(personas_deployment_ise_base_hostname | lower ~ '-mnt-server-1', true) }}.{{ personas_deployment_ise_domain }}"
      hostname: "{{ personas_deployment_mnt1_hostname | default(personas_deployment_ise_base_hostname | lower ~ '-mnt-server-1', true) }}"
      roles:
        - PrimaryMonitoring
      services: []
    - fqdn: "{{ personas_deployment_psn1_hostname | default(personas_deployment_ise_base_hostname | lower ~ '-psn-server-1', true) }}.{{ personas_deployment_ise_domain }}"
      hostname: "{{ personas_deployment_psn1_hostname | default(personas_deployment_ise_base_hostname | lower ~ '-psn-server-1', true) }}"
      roles: []
      services:
        - Session
        - Profiler
    - fqdn: "{{ personas_deployment_psn2_hostname | default(personas_deployment_ise_base_hostname | lower ~ '-psn-server-2', true) }}.{{ personas_deployment_ise_domain }}"
      hostname: "{{ personas_deployment_psn2_hostname | default(personas_deployment_ise_base_hostname | lower ~ '-psn-server-2', true) }}"
      roles: []
      services:
        - Session
        - Profiler

- name: Delete the MNT role from the primary node
  cisco.ise.node_deployment:
    ise_hostname: "{{ personas_deployment_pan1_ip }}"
    ise_username: "{{ personas_deployment_ise_username }}"
    ise_password: "{{ personas_deployment_ise_password }}"
    ise_verify: "{{ personas_deployment_ise_verify }}"
    ise_single_request_timeout: "{{ personas_deployment_ise_single_request_timeout }}"
    ise_version: "{{ personas_deployment_ise_version }}"
    state: present
    hostname: "{{ personas_deployment_pan1_hostname | default(personas_deployment_ise_base_hostname | lower ~ '-pan-server-1', true) }}"
    roles:
      - PrimaryAdmin
    services: []

- name: Wait for primary application server to come up again
  ansible.builtin.pause:
    minutes: 10

- name: Register node 'MNT Server 2' as SecondaryMonitoring
  cisco.ise.node_deployment:
    ise_hostname: "{{ personas_deployment_pan1_ip }}"
    ise_username: "{{ personas_deployment_ise_username }}"
    ise_password: "{{ personas_deployment_ise_password }}"
    ise_verify: "{{ personas_deployment_ise_verify }}"
    ise_single_request_timeout: "{{ personas_deployment_ise_single_request_timeout }}"
    ise_version: "{{ personas_deployment_ise_version }}"
    state: present
    allowCertImport: true
    fqdn: "{{ item.fqdn }}"
    hostname: "{{ item.hostname }}"
    userName: "{{ personas_deployment_ise_username }}"
    password: "{{ personas_deployment_ise_password }}"
    roles: "{{ item.roles }}"
    services: "{{ item.services }}"
  loop:
    - fqdn: "{{ personas_deployment_mnt2_hostname | default(personas_deployment_ise_base_hostname | lower ~ '-mnt-server-2', true) }}.{{ personas_deployment_ise_domain }}"
      hostname: "{{ personas_deployment_mnt2_hostname | default(personas_deployment_ise_base_hostname | lower ~ '-mnt-server-2', true) }}"
      roles:
        - SecondaryMonitoring
      services: []
