---
- name: Deploy Cisco ISE node(s) on Azure
  hosts: localhost
  gather_facts: false
  connection: local
  vars_files:
    ../vars/azure_ise_config.yml
  vars:
    ise_deployment_type: small
    personas_deployment_ise_username: iseadmin
    personas_deployment_ise_password: "Your#1SecretPassword!!"
    personas_deployment_ise_domain: "{{ dnsdomain }}"
    personas_deployment_pan1_ip: 40.70.26.43
    personas_deployment_pan2_ip: 20.98.224.197
    personas_deployment_pan1_hostname: ise-eastus2-n1
    personas_deployment_pan2_hostname: ise-eastus2-n2
  roles:
    - ise_personas
